# Generated by Django 3.0.5 on 2020-04-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmsNavigationLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=999)),
                ('order_number', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Навигационная ссылка CMS',
                'verbose_name_plural': 'Навигационные ссылки CMS',
            },
        ),
    ]
