# Generated by Django 3.0.5 on 2020-04-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20200423_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsnavigationlink',
            name='glyph_icon',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
