# Generated by Django 3.0.5 on 2020-05-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
    ]
