# Generated by Django 3.0.5 on 2020-05-05 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20200505_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'verbose_name': 'Папка', 'verbose_name_plural': 'Папки'},
        ),
    ]
