# Generated by Django 3.0.5 on 2020-06-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20200505_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmsMainInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_notification', models.TextField(default='', verbose_name='Важное уведомление')),
                ('mini_notification1', models.TextField(default='', verbose_name='Уведомление №1')),
                ('mini_notification2', models.TextField(default='', verbose_name='Уведомление №2')),
            ],
        ),
    ]
