# Generated by Django 3.0.5 on 2020-06-04 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_cmsmaininfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cmsmaininfo',
            options={'verbose_name': 'Основная информация по CMS', 'verbose_name_plural': 'Основная информация по CMS'},
        ),
    ]
