# Generated by Django 3.0.5 on 2020-06-23 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_auth', '0006_auto_20200418_1308'),
        ('cms', '0013_appeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_auth.Viewer'),
        ),
    ]
