# Generated by Django 3.0.5 on 2020-04-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0004_auto_20200413_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'verbose_name': 'Аниме', 'verbose_name_plural': 'Список аниме'},
        ),
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.ImageField(upload_to='anime', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='season',
            field=models.IntegerField(default=1, verbose_name='Номер сезона'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title_foreign',
            field=models.CharField(default='', max_length=255, verbose_name='Название на иностранном'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title_rus',
            field=models.CharField(max_length=255, verbose_name='Название на русском'),
        ),
    ]
