# Generated by Django 3.0.5 on 2020-04-15 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0008_auto_20200414_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='anime',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='watch.Anime'),
        ),
    ]
