# Generated by Django 3.0.5 on 2020-04-15 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0011_auto_20200415_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constantgenre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.RemoveField(
            model_name='anime',
            name='genre_list',
        ),
    ]
