# Generated by Django 3.0.5 on 2020-04-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200413_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationlink',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
    ]
