# Generated by Django 3.0.5 on 2020-04-16 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewer',
            options={'verbose_name': 'Зритель', 'verbose_name_plural': 'Зрители'},
        ),
    ]
