# Generated by Django 3.0.5 on 2020-04-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_auth', '0003_auto_20200416_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='value',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
