# Generated by Django 3.0.5 on 2020-04-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_anime_title_foreign'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='season',
            field=models.IntegerField(default=1),
        ),
    ]
