# Generated by Django 3.0.5 on 2020-04-13 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0003_anime_season'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'verbose_name_plural': 'Список аниме'},
        ),
    ]
