# Generated by Django 3.0.5 on 2020-04-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0005_auto_20200414_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='anime',
            name='episodes_quantity',
            field=models.IntegerField(default=12, verbose_name='Количество серий'),
        ),
        migrations.AddField(
            model_name='anime',
            name='start_date',
            field=models.DateField(default='2020-01-01', verbose_name='Дата начала'),
        ),
    ]
