# Generated by Django 3.0.5 on 2020-04-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0006_auto_20200414_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название жанра')),
                ('order_number', models.IntegerField(verbose_name='Порядковый номер')),
            ],
        ),
    ]
