# Generated by Django 3.0.5 on 2020-04-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0007_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр Аниме', 'verbose_name_plural': 'Жанры Аниме'},
        ),
        migrations.AddField(
            model_name='anime',
            name='genre_list',
            field=models.CharField(default='', max_length=999),
        ),
    ]
