# Generated by Django 3.0.5 on 2020-04-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0013_auto_20200416_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constantgenre',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название жанра'),
        ),
    ]
