# Generated by Django 3.0.5 on 2020-06-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0015_anime_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='tags',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Поисковые теги'),
        ),
    ]
