# Generated by Django 3.0.7 on 2020-07-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0018_auto_20200626_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='animecomment',
            name='publish_date',
            field=models.DateTimeField(default='2020-07-08', verbose_name='Дата публикации'),
        ),
    ]
